### ISSUE TITLE
D-pads

### ISSUE THREAD

**Issue by hendursaga** [KW-M/virtual-gamepad-lib#3]
Is there a setting I can set that would allow for two directions (e.g. southwest) to be read from a D-pad, specifically, with a touch device? I tried testing the full and simple examples out, and I couldn't tell if I could hold down more than one "push button" at a time.

Alternatively, is there plans to add 8-direction D-pads, ala Game Master controllers?

**Comment by KW-M** [comment]
Hi. I hadn't originally considered the 8-direction d-pad case, but it will totally work anyway! 

The example gamepad has button tap targets that never overlap, so only one button is ever pressed at a time.
You'd want to edit the gamepad SVG or make a custom one so that the tap targets of each d-pad button (N,S,E,W) overlap in the diagonal corners. Make sure to set `lockTargetWhilePressed: false` in the `ButtonConfig` for each d-pad button passed to `gamepadEmulator.AddDisplayButtonEventListeners()` for this to work.

**Comment by KW-M** [comment]
Something like this: The left d-pad tap target is in red and the top d-pad tap target is green (they overlap in the brown area)
I'll update the example gamepad asset tomorrow & add an example with an 8-way d-pad like this.
<img width="598" alt="Screenshot 2024-10-24 at 7 26 32 PM" src="https://github.com/user-attachments/assets/bc3d0135-7f3c-4509-80bc-0a7792bcdc98">

**Comment by KW-M** [comment]
Hey! 

Sorry, I dropped the ball on this one.
Turns out virtual-gamepad-lib CANNOT do an 8 way d-pad as I described here.
When I tested this, I made the fatal flaw of making the overlapping elements in a parent-child relationship - this works great as I described because of event bubbling in JS, but will only allow one overlapping region! But an 8-way d-pad requires 4 overlaps in a circular loop - so this would never have worked. 

I'll think about how to add this feature for the next release, but it likely won't be based on the solution I described above.

**Comment by KW-M** [comment]
The latest release [v0.3.0](https://github.com/KW-M/virtual-gamepad-lib/releases/tag/v0.3.0) now supports 8-way d-pads along with a bunch of other improvements
Works with the new preset gamepads - see the [simple example](https://kw-m.github.io/virtual-gamepad-lib/simple/index.html)
Also works with custom gamepads - see the [custom gamepads example](https://kw-m.github.io/virtual-gamepad-lib/custom_gamepads/index.html)

> Detail: you can now assign multiple gamepad buttons per tap target using the **buttonIndexes** button touch config option
